Task 9.7
AdamPawlinski/java-script-9.7 pull request #1
Opened 2018-03-19 22:54 UTC by AdamPawlinski

Game finished. Ask for approval.

2018-03-22 14:33 UTC, matwjablonski requested changes

2018-03-22 14:33 UTC, matwjablonski commented on js/script.js
> +var newGameBtn = document.getElementById('js-newGameButton');
between different code sections add empty line - e.g. between functions

2018-03-22 14:33 UTC, matwjablonski commented on js/script.js
> +  }
what will happen when use just click enter without typing a name?

2018-03-22 14:33 UTC, matwjablonski commented on js/script.js
> +    if (playerPick == computerPick) {
always compare also type in javascript

2018-03-22 14:33 UTC, matwjablonski commented on scss/style.scss
> +#js-playerPickElement,
add empty line between css rules

2018-03-23 18:46 UTC, AdamPawlinski commented
Bugs fixed. Please accept changes.

2018-03-23 19:21 UTC, matwjablonski requested changes

2018-03-23 19:21 UTC, matwjablonski commented on js/script.js
> +      if (player.name){
too many nested if statements - you should nest your if only once :)

2018-03-23 20:13 UTC, AdamPawlinski commented
less if statements. Hope that will be okey.

2018-03-24 09:43 UTC, matwjablonski approved these changes

2018-09-11 05:01 UTC, merged